// Static provider catalog. Merged with runtime connection data from API.
// Category labels and ordering mirror OmniRoute provider catalog sections.

export interface ProviderCategory {
  id: string;
  label: string;
  color: string;
  description: string;
}

export interface ProviderMeta {
  id: string;
  displayName: string;
  icon: string;
  textIcon: string;
  iconFile?: string;
  category: string;
  description: string;
  format: string;
  authType: 'none' | 'apikey' | 'oauth' | 'custom';
  prefix: string;
  aliases?: string[];
  isBuiltIn: boolean;
  website?: string;
  color: string;
  serviceKinds?: string[];
  hasFree?: boolean;
  freeNote?: string;
  authHint?: string;
  apiHint?: string;
  inputFormat?: string;
  regionOptions?: string[];
  defaultRegion?: string;
}

export const CATEGORIES: ProviderCategory[] = [
  { id: 'oauth', label: 'OAuth', color: '#3b82f6', description: 'Account and CLI subscription providers that authenticate with OAuth.' },
  { id: 'ide', label: 'IDE', color: '#06b6d4', description: 'Editors with built-in AI subscriptions and imported credentials.' },
  { id: 'free', label: 'Free tier', color: '#22c55e', description: 'Providers with a free or no-auth access path.' },
  { id: 'no-auth', label: 'No auth', color: '#78716c', description: 'Keyless public endpoints or bootstrap-token providers.' },
  { id: 'upstream-proxy', label: 'Upstream proxy', color: '#6366f1', description: 'Proxy and relay surfaces that forward to another upstream.' },
  { id: 'apikey', label: 'API key', color: '#f59e0b', description: 'Managed providers that use bearer API keys.' },
  { id: 'compatible', label: 'Compatible', color: '#f97316', description: 'OpenAI, Anthropic, or Claude Code compatible custom endpoints.' },
  { id: 'web-cookie', label: 'Web cookie', color: '#a855f7', description: 'Browser session, cookie, or web-token based providers.' },
  { id: 'search', label: 'Search', color: '#14b8a6', description: 'Search API providers.' },
  { id: 'webfetch', label: 'Web fetch', color: '#fb923c', description: 'Reader and fetch providers for web content extraction.' },
  { id: 'audio', label: 'Audio', color: '#f43f5e', description: 'Speech-to-text and text-to-speech providers.' },
  { id: 'local', label: 'Local', color: '#10b981', description: 'Local or self-hosted model runtimes.' },
  { id: 'cloud-agent', label: 'Cloud agent', color: '#8b5cf6', description: 'Hosted coding agents and remote execution surfaces.' },
  { id: 'service-account', label: 'Service account', color: '#4285f4', description: 'Cloud providers authenticated with a service-account JSON key.' },
];

export const PROVIDER_CATALOG: ProviderMeta[] = [
  {
    id: 'cx',
    displayName: 'OpenAI Codex',
    icon: 'code',
    textIcon: 'CX',
    iconFile: '/providers/codex.svg',
    category: 'oauth',
    description: 'OpenAI Codex account routed through the OAuth device-code flow.',
    format: 'openai-responses',
    authType: 'oauth',
    prefix: 'cx/',
    isBuiltIn: true,
    website: 'https://openai.com',
    color: '#3b82f6',
    serviceKinds: ['llm'],
  },
  {
    id: 'ag',
    displayName: 'Antigravity',
    icon: 'rocket_launch',
    textIcon: 'AG',
    iconFile: '/providers/antigravity.png',
    category: 'oauth',
    description: 'Google Antigravity account provider with OAuth-backed routing.',
    format: 'antigravity',
    authType: 'oauth',
    prefix: 'ag/',
    isBuiltIn: true,
    website: 'https://antigravity.google',
    color: '#f59e0b',
    serviceKinds: ['llm'],
  },
  {
    id: 'kiro',
    displayName: 'Kiro AI',
    icon: 'psychology_alt',
    textIcon: 'KR',
    iconFile: '/providers/kiro.svg',
    category: 'oauth',
    description: 'Kiro AI via AWS Builder ID, IAM Identity Center (IDC), Google/GitHub social login, imported kiro-cli or AWS SSO tokens, or an external IdP refresh token.',
    format: 'kiro',
    authType: 'oauth',
    prefix: 'kiro/',
    isBuiltIn: true,
    website: 'https://kiro.dev',
    color: '#ff6b35',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Free monthly credit tier when eligible on the upstream account.',
    authHint: 'Use AWS Builder ID device code, Google/GitHub, IDC SSO, or import an existing kiro-cli/AWS SSO cache token.',
  },
  {
    id: 'amazon-q',
    displayName: 'Amazon Q',
    icon: 'cloud',
    textIcon: 'AQ',
    iconFile: '/providers/aws.svg',
    category: 'oauth',
    description: 'Amazon Q Developer via AWS Builder ID, IAM Identity Center (IDC), Google/GitHub social login, imported aws-cli or AWS SSO tokens, or an external IdP refresh token.',
    format: 'kiro',
    authType: 'oauth',
    prefix: 'aq/',
    isBuiltIn: true,
    website: 'https://aws.amazon.com/q/developer/',
    color: '#FF9900',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Free tier available when eligible on the upstream AWS account.',
    authHint: 'Use AWS Builder ID device code, Google/GitHub, IDC SSO, or import an existing aws-cli/AWS SSO cache token.',
  },
  {
    id: 'claude',
    displayName: 'Anthropic Claude',
    icon: 'smart_toy',
    textIcon: 'AN',
    iconFile: '/providers/anthropic-m.png',
    category: 'apikey',
    description: 'Anthropic Claude API provider using an API key.',
    format: 'anthropic',
    authType: 'apikey',
    prefix: 'claude/',
    isBuiltIn: true,
    website: 'https://anthropic.com',
    color: '#d97757',
    serviceKinds: ['llm'],
  },
  {
    id: 'openai',
    displayName: 'OpenAI',
    icon: 'auto_awesome',
    textIcon: 'OA',
    iconFile: '/providers/openai.png',
    category: 'apikey',
    description: 'OpenAI platform API key provider for GPT and reasoning models.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'openai/',
    isBuiltIn: true,
    website: 'https://platform.openai.com',
    color: '#10a37f',
    serviceKinds: ['llm'],
  },
  {
    id: 'gemini',
    displayName: 'Gemini',
    icon: 'diamond',
    textIcon: 'GE',
    iconFile: '/providers/gemini-cli.svg',
    category: 'apikey',
    description: 'Google AI Studio Gemini models through API key authentication.',
    format: 'gemini',
    authType: 'apikey',
    prefix: 'gemini/',
    isBuiltIn: true,
    website: 'https://ai.google.dev',
    color: '#4285f4',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Google AI Studio free quota depends on model and region.',
  },
  {
    id: 'deepseek',
    displayName: 'DeepSeek',
    icon: 'bolt',
    textIcon: 'DS',
    iconFile: '/providers/deepseek.png',
    category: 'apikey',
    description: 'DeepSeek API key provider using OpenAI-compatible chat endpoints.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'deepseek/',
    isBuiltIn: true,
    website: 'https://platform.deepseek.com',
    color: '#4d6bfe',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Free token grants are controlled by the upstream DeepSeek account.',
  },
  {
    id: 'groq',
    displayName: 'Groq',
    icon: 'speed',
    textIcon: 'GQ',
    iconFile: '/providers/groq.png',
    category: 'apikey',
    description: 'Groq low-latency inference for hosted LLM models.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'groq/',
    isBuiltIn: true,
    website: 'https://groq.com',
    color: '#f55036',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Groq free tier limits depend on model and account state.',
  },
  {
    id: 'openrouter',
    displayName: 'OpenRouter',
    icon: 'router',
    textIcon: 'OR',
    iconFile: '/providers/openrouter.png',
    category: 'apikey',
    description: 'OpenRouter multi-model gateway using OpenAI-compatible API keys.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'openrouter/',
    isBuiltIn: true,
    website: 'https://openrouter.ai',
    color: '#f97316',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Free models are available upstream with model-specific limits.',
  },
{
  id: 'mimo',
  displayName: 'Xiaomi MiMo PAYG',
  icon: 'credit_card',
  textIcon: 'MM',
  iconFile: '/providers/mimo.png',
  category: 'apikey',
  description: 'Xiaomi MiMo pay-as-you-go model endpoint.',
  format: 'openai',
  authType: 'apikey',
  prefix: 'mimo/',
  isBuiltIn: true,
  website: 'https://mimo.mi.com',
  color: '#ea580c',
  serviceKinds: ['llm'],
},
{
  id: 'mimo-tp',
  displayName: 'Xiaomi MiMo Token Plan',
  icon: 'token',
  textIcon: 'MT',
  iconFile: '/providers/mimo-tp.png',
  category: 'apikey',
  description: 'MiMo monthly token-plan connection pool for high-volume routing.',
  format: 'openai',
  authType: 'apikey',
  prefix: 'mimo-tp/',
  isBuiltIn: true,
  website: 'https://mimo.mi.com',
  color: '#f59e0b',
  serviceKinds: ['llm'],
},
  {
    id: 'qwencloud',
    displayName: 'QwenCloud',
    icon: 'psychology',
    textIcon: 'QC',
    iconFile: 'https://img.alicdn.com/imgextra/i2/O1CN01F3ylft1COZGWn6kop_!!6000000000071-2-tps-48-48.png',
    category: 'apikey',
    description: 'Alibaba QwenCloud DashScope API provider using OpenAI-compatible responses endpoints.',
    format: 'openai-responses',
    authType: 'apikey',
    prefix: 'qwencloud/',
    isBuiltIn: true,
    website: 'https://www.qwencloud.com',
    color: '#5A31F4',
    serviceKinds: ['llm'],
  },
  {
    id: 'zai',
    displayName: 'Z.ai GLM',
    icon: 'psychology',
    textIcon: 'ZA',
    iconFile: '/providers/glm.png',
    category: 'apikey',
    description: 'Z.ai GLM endpoint exposed through Claude-compatible messages.',
    format: 'claude',
    authType: 'apikey',
    prefix: 'zai/',
    isBuiltIn: false,
    website: 'https://z.ai',
    color: '#2563eb',
    serviceKinds: ['llm'],
  },
  {
    id: 'oc-zen',
    displayName: 'OpenCode Zen',
    icon: 'opencode',
    textIcon: 'OZ',
    iconFile: '/providers/opencode-zen.png',
    category: 'apikey',
    description: 'OpenCode Zen API-key tier exposed as a gateway provider.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'oc-zen/',
    isBuiltIn: true,
    website: 'https://opencode.ai/zen',
    color: '#6366f1',
    serviceKinds: ['llm'],
    hasFree: true,
  },
  {
    id: 'oc-go',
    displayName: 'OpenCode Go',
    icon: 'opencode',
    textIcon: 'OG',
    iconFile: '/providers/opencode-go.png',
    category: 'apikey',
    description: 'OpenCode Go API-key tier for Qwen-oriented routing.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'oc-go/',
    isBuiltIn: true,
    website: 'https://opencode.ai/go',
    color: '#6366f1',
    serviceKinds: ['llm'],
    hasFree: true,
  },
  {
    id: 'elevenlabs',
    displayName: 'ElevenLabs',
    icon: 'record_voice_over',
    textIcon: 'EL',
    iconFile: '/providers/elevenlabs.png',
    category: 'audio',
    description: 'ElevenLabs text-to-speech synthesis provider.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'elevenlabs/',
    isBuiltIn: true,
    website: 'https://elevenlabs.io',
    color: '#6c47ff',
    serviceKinds: ['tts'],
  },
  {
    id: 'deepgram',
    displayName: 'Deepgram',
    icon: 'mic',
    textIcon: 'DG',
    iconFile: '/providers/deepgram.png',
    category: 'audio',
    description: 'Deepgram speech-to-text transcription provider.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'deepgram/',
    isBuiltIn: true,
    website: 'https://deepgram.com',
    color: '#13ef93',
    serviceKinds: ['stt'],
  },
  {
	id: 'oc',
    displayName: 'OpenCode Free',
    icon: 'terminal',
    textIcon: 'OC',
    iconFile: '/providers/opencode.png',
    category: 'no-auth',
    description: 'Public OpenCode endpoint with no API key required.',
    format: 'openai',
    authType: 'none',
    prefix: 'oc/',
    isBuiltIn: true,
    website: 'https://opencode.ai',
    color: '#e87040',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'No API key required. Public endpoint limits apply.',
  },
{
  id: 'mimocode',
  displayName: 'MiMoCode Free',
  icon: 'devices',
  textIcon: 'MC',
  iconFile: '/providers/mimo-free.png',
  category: 'no-auth',
    description: 'MiMoCode free tier with bootstrap JWT activation.',
    format: 'openai',
    authType: 'none',
    prefix: 'mimocode/',
    isBuiltIn: true,
    website: 'https://mimo.mi.com',
    color: '#ff6b35',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'No API key required. Bootstrap tokens are generated automatically.',
  },
  {
    id: 'cf',
    displayName: 'Cloudflare Workers AI',
    icon: 'cloud',
    textIcon: 'CF',
    iconFile: '/providers/cloudflare.png',
    category: 'apikey',
    description: 'Cloudflare Workers AI Gateway with OpenAI-compatible API. Supports @cf/ models.',
    format: 'openai',
    authType: 'custom',
    prefix: 'cf/',
    isBuiltIn: true,
    website: 'https://developers.cloudflare.com/ai-gateway/',
    color: '#F38020',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Workers AI free tier: 10,000 neurons/day per account.',
    inputFormat: 'pipe',
  },
  {
    id: 'glm',
    displayName: 'Z.ai GLM',
    icon: 'code',
    textIcon: 'GL',
    iconFile: '/providers/glm.png',
    category: 'apikey',
    description: 'Zhipu Z.ai GLM OpenAI-compatible chat endpoint.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'glm/',
    isBuiltIn: true,
    website: 'https://z.ai',
    color: '#2563EB',
    serviceKinds: ['llm'],
  },
  {
    id: 'minimax',
    displayName: 'MiniMax',
    icon: 'memory',
    textIcon: 'MM',
    iconFile: '/providers/minimax.png',
    category: 'apikey',
    description: 'MiniMax OpenAI-compatible chat and coding models.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'minimax/',
    isBuiltIn: true,
    website: 'https://www.minimax.io',
    color: '#7C3AED',
    serviceKinds: ['llm'],
  },
  {
    id: 'kimi',
    displayName: 'Kimi',
    icon: 'psychology',
    textIcon: 'KM',
    iconFile: '/providers/kimi.png',
    category: 'apikey',
    description: 'Moonshot Kimi OpenAI-compatible chat endpoint.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'kimi/',
    isBuiltIn: true,
    website: 'https://platform.moonshot.ai',
    color: '#1E3A8A',
    serviceKinds: ['llm'],
  },
  {
    id: 'mistral',
    displayName: 'Mistral',
    icon: 'air',
    textIcon: 'MI',
    iconFile: '/providers/mistral.png',
    category: 'apikey',
    description: 'Mistral AI OpenAI-compatible chat endpoint.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'mistral/',
    isBuiltIn: true,
    website: 'https://mistral.ai',
    color: '#FF7000',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Free Experiment tier: rate-limited access, no credit card.',
  },
  {
    id: 'cerebras',
    displayName: 'Cerebras',
    icon: 'memory',
    textIcon: 'CB',
    iconFile: '/providers/cerebras.png',
    category: 'apikey',
    description: 'Cerebras fast inference API with OpenAI-compatible chat.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'cerebras/',
    isBuiltIn: true,
    website: 'https://inference.cerebras.ai',
    color: '#FF4F00',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Free trial: 1M tokens/day, 30K TPM, 5 RPM — no credit card.',
  },
  {
    id: 'together',
    displayName: 'Together AI',
    icon: 'group_work',
    textIcon: 'TG',
    iconFile: '/providers/together.png',
    category: 'apikey',
    description: 'Together AI serverless GPU inference, OpenAI-compatible.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'together/',
    isBuiltIn: true,
    website: 'https://www.together.ai',
    color: '#0F6FFF',
    serviceKinds: ['llm'],
  },
  {
    id: 'fireworks',
    displayName: 'Fireworks AI',
    icon: 'local_fire_department',
    textIcon: 'FW',
    iconFile: '/providers/fireworks.png',
    category: 'apikey',
    description: 'Fireworks AI fast inference for open-weight models.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'fireworks/',
    isBuiltIn: true,
    website: 'https://fireworks.ai',
    color: '#7B2EF2',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: '$1 free starter credits on signup.',
  },
  {
    id: 'novita',
    displayName: 'Novita AI',
    icon: 'auto_awesome',
    textIcon: 'NV',
    iconFile: '/providers/novita.svg',
    category: 'apikey',
    description: 'Novita AI OpenAI-compatible inference endpoint.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'novita/',
    isBuiltIn: true,
    website: 'https://novita.ai',
    color: '#FF4081',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: '$0.50 trial credits on signup.',
  },
  {
    id: 'lambda',
    displayName: 'Lambda',
    icon: 'bolt',
    textIcon: 'LA',
    iconFile: '/providers/lambda.svg',
    category: 'apikey',
    description: 'Lambda AI OpenAI-compatible chat completions on cloud GPUs.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'lambda/',
    isBuiltIn: true,
    website: 'https://lambda.ai',
    color: '#7C3AED',
    serviceKinds: ['llm'],
  },
  {
    id: 'pollinations',
    displayName: 'Pollinations AI',
    icon: 'local_florist',
    textIcon: 'PO',
    iconFile: '/providers/pollinations.svg',
    category: 'apikey',
    description: 'Pollinations AI multi-modal OpenAI-compatible API (free tier available).',
    format: 'openai',
    authType: 'apikey',
    prefix: 'pollinations/',
    isBuiltIn: true,
    website: 'https://pollinations.ai',
    color: '#4CAF50',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Free keyless tier for openai, qwen-coder, mistral, deepseek, etc.',
  },
{
  id: 'zenmux',
  displayName: 'ZenMux',
  icon: 'swap_horiz',
  textIcon: 'ZM',
  iconFile: '/providers/zenmux.svg',
  category: 'apikey',
    description: 'ZenMux OpenAI-compatible API gateway with free and paid tiers.',
    format: 'openai',
    authType: 'apikey',
    prefix: 'zenmux/',
    isBuiltIn: true,
    website: 'https://zenmux.ai',
    color: '#8b5cf6',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'Free tier includes Gemini 3 Flash, DeepSeek V3.2, Grok 4.1 Fast, Mistral Large, and more.',
    apiHint: 'Get your API key at https://zenmux.ai',
  },
{
  id: 'zenmux-free',
  displayName: 'ZenMux Free',
  icon: 'swap_horiz',
  textIcon: 'ZF',
  iconFile: '/providers/zenmux-free.svg',
  category: 'apikey',
  description: 'ZenMux free-tier OpenAI-compatible API gateway.',
  format: 'openai',
  authType: 'apikey',
  prefix: 'zenmux-free/',
  aliases: ['zxfree'],
  isBuiltIn: true,
  website: 'https://zenmux.ai',
  color: '#059669',
  serviceKinds: ['llm'],
  hasFree: true,
  freeNote: 'Free tier access to ZenMux models.',
  apiHint: 'Get your API key at https://zenmux.ai',
},
  {
    id: 'copilot',
    displayName: 'GitHub Copilot',
    icon: 'code',
    textIcon: 'CP',
    iconFile: '/providers/copilot.png',
    category: 'oauth',
    description: 'GitHub Copilot via the OAuth device-code flow. Authorize on another device to let AxonRouter request a Copilot access token.',
    format: 'openai',
    authType: 'oauth',
    prefix: 'copilot/',
    isBuiltIn: true,
    website: 'https://github.com/copilot',
    color: '#6e5494',
    serviceKinds: ['llm'],
  },
  {
    id: 'codebuddy',
    displayName: 'CodeBuddy',
    icon: 'smart_toy',
    textIcon: 'CB',
    iconFile: '/providers/codebuddy.png',
    category: 'oauth',
    description: 'Tencent CodeBuddy via browser OAuth polling flow.',
    format: 'openai',
    authType: 'oauth',
    prefix: 'codebuddy/',
    isBuiltIn: true,
    website: 'https://www.codebuddy.ai',
    color: '#006EFF',
    serviceKinds: ['llm'],
  },
  {
    id: 'grok-cli',
    displayName: 'Grok CLI (Grok Build)',
    icon: 'terminal',
    textIcon: 'GC',
    iconFile: '/providers/grok-cli.png',
    category: 'oauth',
    description: 'Grok CLI via OAuth device-code flow or imported access token. Routes to the Grok Build CLI proxy.',
    format: 'grok-cli',
    authType: 'oauth',
    prefix: 'grok-cli/',
    isBuiltIn: true,
    website: 'https://x.ai',
    color: '#1a1a1a',
    serviceKinds: ['llm'],
  },
  {
    id: 'vertex',
    displayName: 'Google Vertex AI',
    icon: 'cloud',
    textIcon: 'VA',
    iconFile: '/providers/vertex.png',
    category: 'service-account',
    description: 'Google Vertex AI OpenAI-compatible endpoint via service-account JSON key.',
    format: 'openai',
    authType: 'custom',
    prefix: 'vertex/',
    isBuiltIn: true,
    website: 'https://cloud.google.com/vertex-ai',
    color: '#4285F4',
    serviceKinds: ['llm'],
    hasFree: true,
    freeNote: 'GCP free tier quota depends on model and region.',
  },
{
  id: 'bedrock',
  displayName: 'Amazon Bedrock Mantle',
  icon: 'cloud',
  textIcon: 'BR',
  iconFile: '/providers/bedrock.svg',
  category: 'apikey',
  description: 'Amazon Bedrock Mantle OpenAI-compatible endpoint with bearer-token auth.',
  format: 'openai',
  authType: 'apikey',
  prefix: 'bedrock/',
  isBuiltIn: true,
  website: 'https://aws.amazon.com/bedrock',
  color: '#FF9900',
  serviceKinds: ['llm'],
  regionOptions: ['us-east-1', 'us-east-2', 'us-west-2', 'eu-west-1', 'eu-west-2', 'eu-central-1', 'eu-south-1', 'eu-north-1', 'ap-northeast-1', 'ap-south-1', 'ap-southeast-3', 'sa-east-1'],
  defaultRegion: 'us-east-1',
},
{
  id: 'devin',
  displayName: 'Devin CLI',
  icon: 'terminal',
  textIcon: 'DV',
  iconFile: '/providers/devin.svg',
  category: 'cloud-agent',
  description: 'Devin CLI agent via the devin acp subprocess. Requires a Windsurf / Devin API key or CLI_DEVIN_BIN override.',
  format: 'devin-cli',
  authType: 'apikey',
  prefix: 'devin/',
  isBuiltIn: true,
  website: 'https://cli.devin.ai',
  color: '#111827',
  serviceKinds: ['llm'],
  authHint: 'Windsurf / Devin API key or CLI_DEVIN_BIN override.',
},
{
  id: 'qoder',
  displayName: 'Qoder',
  icon: 'water_drop',
  textIcon: 'QD',
  iconFile: '/providers/qoder.png',
  category: 'apikey',
  description: 'Qoder dual-mode provider: DashScope API key for HTTP transport, or Qoder PAT (pt-...) for local qodercli transport.',
  format: 'qoder',
  authType: 'apikey',
  prefix: 'qoder/',
  isBuiltIn: true,
  website: 'https://qoder.com',
  color: '#6366f1',
  serviceKinds: ['llm'],
  hasFree: true,
  authHint: 'DashScope API key or Qoder PAT (pt-...) for CLI transport.',
},
];

// Provider aliases are loaded from the backend so legacy URLs/IDs continue to work.
// The frontend does not keep a redundant copy of alias data; it populates this map
// at runtime from the API response and uses it only for catalog lookups.
let PROVIDER_ALIASES: Record<string, string> = {};

/**
 * loadProviderAliases populates the alias lookup from the backend canonical list.
 * Each backend provider object has `id` (canonical) and optional `aliases` array.
 * The reverse map (alias -> canonical) is rebuilt so resolveProviderCatalogId works.
 */
export function loadProviderAliases(providers: { id: string; aliases?: string[] }[]): void {
	const map: Record<string, string> = {};
	for (const p of providers) {
		if (p.aliases) {
			for (const alias of p.aliases) {
				map[alias] = p.id;
			}
		}
	}
	PROVIDER_ALIASES = { ...PROVIDER_ALIASES, ...map };
}

export function resolveProviderCatalogId(id: string): string {
  return PROVIDER_ALIASES[id] ?? id;
}

export function getCategoryById(id: string): ProviderCategory | undefined {
  return CATEGORIES.find((category) => category.id === id);
}

export function getProviderMeta(id: string): ProviderMeta | undefined {
	const catalogId = resolveProviderCatalogId(id);
	return PROVIDER_CATALOG.find((provider) => provider.id === catalogId);
}

export function getComboMeta(id: string, name?: string): ProviderMeta {
	const display = name || id;
	return {
		id,
		displayName: display,
		icon: 'layers',
		textIcon: display.slice(0, 2).toUpperCase(),
		iconFile: '/providers/combo.svg',
		category: 'compatible',
		description: '',
		format: 'openai',
		authType: 'apikey',
		prefix: `${id}/`,
		isBuiltIn: false,
		color: '#f59e0b',
	};
}

export function getProviderIconSrc(id: string): string | null {
  return getProviderMeta(id)?.iconFile ?? null;
}

export function getCategoryForProvider(id: string): string {
  return getProviderMeta(id)?.category ?? 'compatible';
}

export function getCategoryColor(categoryId: string): string {
  return getCategoryById(categoryId)?.color ?? '#888888';
}

export function getStatusDotColor(status: string): string {
  switch (status) {
    case 'ready': return '#10b981';
    case 'rate_limited': return '#f59e0b';
    case 'quota_exhausted': return '#f97316';
    case 'disabled': return '#6b7280';
    default: return '#6b7280';
  }
}

export function getStatusVariant(status: string): 'default' | 'secondary' | 'destructive' | 'outline' {
  switch (status) {
    case 'ready': return 'default';
    case 'rate_limited': case 'quota_exhausted': return 'secondary';
    case 'disabled': return 'outline';
    default: return 'secondary';
  }
}

export function getStatusLabel(status: string): string {
  switch (status) {
    case 'ready': return 'Ready';
    case 'rate_limited': return 'Rate limited';
    case 'quota_exhausted': return 'Quota exhausted';
    case 'disabled': return 'Disabled';
    default: return status;
  }
}
