// ponytail: this file is dead code — Tailwind v4 @tailwindcss/vite reads @theme from app.css, not this config.
// Kept in sync for reference only. Delete if it causes confusion.
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#ec4899',
        'on-primary': '#ffffff',
        ink: '#e4e4e7',
        body: '#a1a1aa',
        mute: '#71717a',
        hairline: '#27272a',
        'hairline-strong': '#3f3f46',
        canvas: '#18181b',
        'canvas-soft': '#0f0f12',
        'canvas-soft-2': '#1e1e22',
        link: '#f472b6',
        'link-deep': '#ec4899',
        'link-bg-soft': '#ec489920',
        error: '#f87171',
        'error-soft': '#f8717120',
        'error-deep': '#ef4444',
        warning: '#fbbf24',
        'warning-soft': '#fbbf2420',
        'warning-deep': '#f59e0b',
        violet: '#7928ca',
        'violet-soft': '#d8ccf1',
        'violet-deep': '#4c2889',
        cyan: '#50e3c2',
        'cyan-soft': '#aaffec',
        'cyan-deep': '#29bc9b',
        'highlight-pink': '#ff0080',
        'highlight-magenta': '#eb367f',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'JetBrains Mono', 'monospace'],
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '40px',
        '3xl': '48px',
        '4xl': '64px',
        '5xl': '96px',
        '6xl': '128px',
        section: '192px',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        'pill-sm': '64px',
        pill: '100px',
        full: '9999px',
      },
      maxWidth: {
        container: '1400px',
      },
    },
  },
  plugins: [],
}
