// ponytail: this file is dead code — Tailwind v4 @tailwindcss/vite reads @theme from app.css, not this config.
// Kept in sync for reference only. Delete if it causes confusion.
/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{html,js,svelte,ts}'],
  theme: {
    extend: {
      colors: {
        primary: '#171717',
        'on-primary': '#ffffff',
        ink: '#171717',
        body: '#4d4d4d',
        mute: '#888888',
        hairline: '#ebebeb',
        'hairline-strong': '#a1a1a1',
        canvas: '#ffffff',
        'canvas-soft': '#fafafa',
        'canvas-soft-2': '#f5f5f5',
        link: '#0070f3',
        'link-deep': '#0761d1',
        'link-bg-soft': '#d3e5ff',
        error: '#ee0000',
        'error-soft': '#f7d4d6',
        'error-deep': '#c50000',
        warning: '#f5a623',
        'warning-soft': '#ffefcf',
        'warning-deep': '#ab570a',
        violet: '#7928ca',
        'violet-soft': '#d8ccf1',
        'violet-deep': '#4c2889',
        cyan: '#50e3c2',
        'cyan-soft': '#aaffec',
        'cyan-deep': '#29bc9b',
        'highlight-pink': '#ff0080',
        'highlight-magenta': '#eb367f',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', 'sans-serif'],
        mono: ['Geist Mono', 'JetBrains Mono', 'monospace'],
      },
      spacing: {
        xxs: '4px',
        xs: '8px',
        sm: '12px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        '2xl': '40px',
        '3xl': '48px',
        '4xl': '64px',
        '5xl': '96px',
        '6xl': '128px',
        section: '192px',
      },
      borderRadius: {
        none: '0px',
        xs: '4px',
        sm: '6px',
        md: '8px',
        lg: '12px',
        xl: '16px',
        'pill-sm': '64px',
        pill: '100px',
        full: '9999px',
      },
      maxWidth: {
        container: '1400px',
      },
    },
  },
  plugins: [],
}
